// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT7rg2F-Qva8kcX_QJscOClBgoshvcCSE',
    appId: '1:930297461357:web:9b1f664c6c99e4fbc41d64',
    messagingSenderId: '930297461357',
    projectId: 'campus-navigator-l8eyq',
    authDomain: 'campus-navigator-l8eyq.firebaseapp.com',
    storageBucket: 'campus-navigator-l8eyq.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArzNPD7VSyJR7OCJV7S5Ehxs9aJpWM828',
    appId: '1:930297461357:android:e44817294b9d6ea9c41d64',
    messagingSenderId: '930297461357',
    projectId: 'campus-navigator-l8eyq',
    storageBucket: 'campus-navigator-l8eyq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGiiOTHxu5sz6jbPJyBXDN4d9PUUkTb1Q',
    appId: '1:930297461357:ios:938e852051572f2cc41d64',
    messagingSenderId: '930297461357',
    projectId: 'campus-navigator-l8eyq',
    storageBucket: 'campus-navigator-l8eyq.firebasestorage.app',
    iosBundleId: 'com.example.dissertation',
  );
}
